name: create tag and relese

on:
  pull_request:
    types: [closed]
jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'PR') && startsWith(github.base_ref, 'master')
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_and_prepare_release
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN:  ${{ secrets.PAT_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: "v8.4.0"
      - name: Display
        run: echo ${{ steps.tag_and_prepare_release.outputs.new_tag }}
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          name:  ${{ steps.tag_and_prepare_release.outputs.new_tag }}
          tag: ${{ steps.tag_and_prepare_release.outputs.new_tag }}
          body: See the <a href="https://github.com/akshith-gunasheelan/oneview-golang/blob/master/CHANGELOG.md">CHANGELOG.md</a> for details.
          token:  ${{secrets.PAT_TOKEN}} 
          

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Create Draft Release
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: <tofill>
#         release_name: <tofill>
#         draft: true
#         prerelease: false

#     - uses: actions/upload-release-asset@v1.0.1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ./my-artifact.zip
#         asset_name: my-artifact.zip
#         asset_content_type: application/zip

#     - uses: eregon/publish-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         release_id: ${{ steps.create_release.outputs.id }}

